services:    
    product-node:
      env_file: 
       - ../docker/environments/dev.env
      networks:
       - shared-swarm-net-dev
    

    product-db:
      # ports:
      #    - 27017:27017
      networks:
       - shared-swarm-net-dev

    # filebeat:
    #   networks:
    #      - shared-swarm-net-dev

