services:    
    product-node:
      env_file: 
       - environments/${TARGETENV}.env
      expose: 
        - 8091
      networks:
       - mynetwork-dev
    
   #  product-node-2:
   #     extends:
   #      service: product-node-1
   #     env_file: 
   #      - environments/${TARGETENV}.env

   #  product-node-3:
   #     extends:
   #      service: product-node-1
   #     env_file: 
   #        - environments/${TARGETENV}.env

    
    product-db:
      ports:
         - 27017:27017
      networks:
       - mynetwork-dev