services:    
    product-node:
      env_file: 
       - environments/${TARGETENV}.env
      expose: 
        - 8091
      networks:
       - mynetwork-dev
    
    
    product-db:
      ports:
         - 27017:27017
      networks:
       - mynetwork-dev