services:    
    product-node-1:
      env_file: 
       - dev.env
      environment:
       - APP_HTTP_PORT=8091
      ports: 
        - 8091:8091
      networks:
       - mynetwork-dev
    
    product-node-2:
     env_file: 
       - dev.env
     environment:
       - APP_HTTP_PORT=8092
     ports: 
        - 8092:8092
     networks:
       - mynetwork-dev

    product-node-3:
     env_file: 
       - dev.env
     environment:
       - APP_HTTP_PORT=8093
     ports: 
        - 8093:8093
     networks:
       - mynetwork-dev
    
    product-db:
      ports:
         - 27017:27017
      networks:
       - mynetwork-dev