services:    
    product-node-1:
      env_file: 
       - environments/dev.env
      expose: 
        - 8091
      networks:
       - mynetwork-dev
    
    product-node-2:
       extends:
        service: product-node-1
       env_file: 
        - environments/dev.env

    product-node-3:
       extends:
        service: product-node-1
       env_file: 
          - environments/dev.env

    
    product-db:
      ports:
         - 27017:27017
      networks:
       - mynetwork-dev